### PR TITLE
All images are now visible on one page of the README

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This way, repository will be more attractive.

### CODE REVIEW

**Review by ryukinix — APPROVED** [review]
I love it. Thank you!

**Comment by ryukinix** [comment]
Wow, you are the man behind ultralisp!!!! I LOVE THIS PROJECT!

**Comment by svetlyak40wt** [comment]
> Wow, you are the man behind ultralisp!!!! I LOVE THIS PROJECT!

You can join the project. I need your help!

**Comment by ryukinix** [comment]
> You can join the project. I need your help!

Interesting! I'd love to help

If you are using sbcl, how about we have a quick talk?
```
(ql:quickload :lisp-chat)
(lisp-chat-client:main)
```
Let's see if this works for you. I'm waiting at `chat.lerax.me:5558`. You can log via `netcat` as alternative.

**Comment by svetlyak40wt** [comment]
It does not work. Raises this error after I enter a nickname:

```
The alien function "rl_replace_line" is undefined.
   [Condition of type SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "server broadcast" RUNNING {100DF95B93}>)

Backtrace:
 0: ("undefined function")
 1: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN LISP-CHAT-CLIENT::RECEIVE-MESSAGE))
 2: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN LISP-CHAT-CLIENT::RECEIVE-MESSAGE) {4E7567B}> #<SB-THREAD:MUTEX "io mutex" owner: #<SB-THREAD:THREAD "server broadcast" RUNN..
 4: (LISP-CHAT-CLIENT::RECEIVE-MESSAGE "|20:22:50| [@server]: The user \"svetlyak40wt\" joined to the party!")
 5: (LISP-CHAT-CLIENT::SERVER-LISTENER #<USOCKET:STREAM-USOCKET {100DC5FA83}>)
 6: (LISP-CHAT-CLIENT::SERVER-BROADCAST #<USOCKET:STREAM-USOCKET {100DC5FA83}>)
 7: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 8: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 9: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
11: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {4E75D6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "..
12: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "server broadcast" RUNNING {100DF95B93}> NIL #<FUNCTION LISP-CHAT-CLIENT::SERVER-BROADCAST> (#<USOCKET:STREAM-USOCKET {100DC5FA83}>))
13: ("foreign function: call_into_lisp")
14: ("foreign function: new_thread_trampoline")
15: ("foreign function: _pthread_body")
16: ("foreign function: _pthread_body")
17: ("foreign function: thread_start")
```

**Pull request merged**
